### ISSUE TITLE
Option to skip validation for Node10

### ISSUE THREAD

**Issue by fubhy** [arethetypeswrong/arethetypeswrong.github.io#112]
Hi. Is there an option to entirely skip validation for Node10? It's possible to run it with `--ignore-rules no-resolution` but unless I'm wrong that also skips that rule for the other categories, correct?

**Comment by andrewbranch** [comment]
This is more or less something I have been wanting/planning for some time, but I think I want to implement it differently from `--ignore-rules`. I think the results for every resolution option should always be _visible_, but you should be able to control the criteria for a passing/failing exit code. In addition to some kind of granular config, I was imagining that this could open up some kinds of presets/profiles, so a project could say “show me all the results, enforcing that I comply with the `esm-only` profile.” I can see different projects wanting to validate against at least these profiles:

- strict / max-compat (all rules, all entrypoints, all resolution modes, like today)
- modern (ignore node10)
- esm-only (ignore node10 and node16-cjs)

**Comment by markerikson** [comment]
Yes, that would be wonderful!

Here's another slightly different scenario to toss out there.

For React-Redux, we've got a couple alternate entry points.  React-Redux v8 had `"react-redux/next"`, v9 will have `"react-redux/compat"`.  v9 is where we're adding `package.exports`.

I'm generating the right bundles and setup for `package.exports` to work, but that `/compat` entry point _won't_ work under Node10 because I'm not writing a named file to disk in that location.  That's intentional.  But, that means I've had to disable the check entirely with `--ignore-rules no-resolution`.  It'd be nice if I could just do it for the one entry point or something.

**Comment by benmccann** [comment]
It would be nice if it looked at the `engines` field in `package.json`. My package specifies that it only supports Node 16+ via the `engines` field, so it makes sense to just skip the Node 10 resolution in that case

**Comment by ari-becker** [comment]
Just to provide another data point - we have both a design library, a web frontend, and an Electron-based app. Until Electron fully supports ESM, it's stuck on `moduleResolution: node`, and the web frontend uses `moduleResolution: bundler`. I'd love to add ATTW to CI, but I'd like to skip validation for `node16` and only verify that it works with `node` and `bundler`, since those are the only module resolution types we use.

**Comment by MilanKovacic** [comment]
> My package specifies that it only supports Node 16+ via the `engines` field, so it makes sense to just skip the Node 10 resolution in that case

It is possible for consumers to have typescript moduleResolution set to node10 — regardless of the Node version, in which case the types will be broken.

**Comment by jakeboone02** [comment]
Has there been any development on this? @markerikson I'm having the same issue as you mentioned here: https://github.com/arethetypeswrong/arethetypeswrong.github.io/issues/112#issuecomment-1796482963. I have some endpoints in package.json that won't (and shouldn't) resolve when `npm pack`'d. I want to use `--ignore-rules no-resolution` but only for specific endpoints.

**Comment by Tobbe** [comment]
I needed this feature too. So what I did as a workaround was to write a script that:
1. Runs attw and tells it to output json
2. Redirect the json output to a file
3. Reads that file and parses it into an object
4. Reads the reported errors and reports success if all the errors reported are just node10 errors.

You can look at the script here:
https://github.com/redwoodjs/redwood/blob/d39d278dd47697f2b065888f595d9b0e459a64c7/packages/auth/attw.ts

I wish I didn't have to write the output to a file, and then read and parse that file. But I could never get it to work just straight up reading the output of attw.

**Comment by ArielBenichou** [comment]
Is there any update on this? can we have a flag  `--skip node10` or something?
thanks.

**Comment by tordans** [comment]
For those who come here by searching for `node10`, since https://github.com/arethetypeswrong/arethetypeswrong.github.io/pull/201 was merged the docs now show the profiles https://github.com/arethetypeswrong/arethetypeswrong.github.io/tree/main/packages/cli#profiles section which can be used to skip the validation for node10.

I created https://github.com/arethetypeswrong/arethetypeswrong.github.io/pull/235 to make this connection easier.
