### ISSUE TITLE
Incorrectly passing when types missing in package exports

### ISSUE THREAD

**Issue by benasher44** [arethetypeswrong/arethetypeswrong.github.io#170]
attw reports highlight-words as passing, but TS can't find the types with moduleResolution set to Bundler. I opened a PR with a fix in tricinel/highlight-words#36, and we're not sure whose right. If attw is right, then I suppose I should file a TS bug?

**Comment by andrewbranch** [comment]
It looks like the change in your PR is actually taking advantage of a TS bug, https://github.com/microsoft/TypeScript/issues/50762. Nothing should ever go after `default` because all resolvers match `default` and you’re not supposed to try any conditions after matching one, even if the lookup for that condition fails. I’m not sure why attw is passing without that though; I’ll take a look.

**Comment by andrewbranch** [comment]
Looking at the trace details on https://arethetypeswrong.github.io/?p=highlight-words%401.2.2, I can’t see anything that looks incorrect. Can you share a repro of it not working in `tsc`?

**Comment by benasher44** [comment]
Ah you know what. I'm on highlight-words 1.2.1, and types were fixed in 1.2.2 🤦 . Closing!
