### ISSUE TITLE
v16 fails when packing a directory

### ISSUE THREAD

**Issue by jamesgpearce** [arethetypeswrong/arethetypeswrong.github.io#179]
(using NPM)

v0.15.3:
```
% npx attw --pack dist
No problems found 🌟
```

0.16.0:
```
% npx attw --pack dist
error while checking file:
Command failed: npm pack dist/tinybase-5.0.0-beta.27.tgz
```

**Comment by ericcornelissen** [comment]
The problem seems to stem from [this change](https://github.com/arethetypeswrong/arethetypeswrong.github.io/compare/%40arethetypeswrong/core%400.15.1...%40arethetypeswrong/cli%400.16.0#diff-852d90245bbe147114049b7940720369a5dd1c564e5d1ab29b1bf8eae193cef3R13), where `${filename}` causes the error. Omitting it makes the error go away, restoring [the previous behavior](https://github.com/arethetypeswrong/arethetypeswrong.github.io/compare/%40arethetypeswrong/core%400.15.1...%40arethetypeswrong/cli%400.16.0#diff-2fb448d11702324cc59d657d5945d59cd325540eb87b71f2e66a5bc01ada834cL184). From the [npm-pack](https://docs.npmjs.com/cli/v10/commands/npm-pack) docs it seems that the named argument should be the name of a package rather than a filename, but in either case I don't think this is needed at all for npm.

**Comment by RobinTail** [comment]
the letter `v` is missing in the filename

```
$ attw --pack
...
ENOENT: no such file or directory, open 'express-zod-api-20.1.0.tgz'
$ ls
express-zod-api-v20.1.0.tgz
```

**Comment by RobinTail** [comment]
Workaround for `yarn attw --pack`:

```sh
npm pack
yarn attw *.tgz
rm *.tgz
```
