### ISSUE TITLE
Doesn’t check that imports inside the package work

### ISSUE THREAD

**Issue by jedwards1211** [arethetypeswrong/arethetypeswrong.github.io#22]
When I [check `antlr@4.12.0`](https://arethetypeswrong.github.io/?p=antlr4%404.12.0) it appears to show that everything is okay, and I can use that package with `node` module resolution.  But when I try to use that package with `nodenext` module resolution, I get errors like `Module '"antlr4"' has no exported member 'CommonTokenStream'.`

`CommonTokenStream` shows up in the `node16-esm` resolutions on arethetypeswrong so it seems like it may not be matching the behavior of tsc 5.0.3.  That or maybe there's a bug in tsc?  The docs don't make it very clear what I should expect tsc to do in this case.

I haven't figured out what I would need to change in a PR to `antlr4` but I've been [asking around](https://github.com/microsoft/TypeScript/issues/53636#issuecomment-1494387718).  In addition to needing better package authoring guidance from the docs, it would be good if arethetypeswrong catches problems like this.

**Comment by andrewbranch** [comment]
Not every problem is a module resolution / kind detection problem, and this doesn’t really try to go beyond module resolution at this point. What code is giving you an error?

**Comment by jedwards1211** [comment]
Okay I had a wise idea, I figured out how to enable module resolution tracing and I think I figured out the problem:

```
======== Resolving module './CharStreams' from '/Users/andy/antlr/node_modules/antlr4/src/antlr4/index.d.ts'. ========
Explicitly specified module resolution kind: 'NodeNext'.
Resolving in ESM mode with conditions 'import', 'types', 'node'.
Loading module as file / folder, candidate module location '/Users/andy/antlr/node_modules/antlr4/src/antlr4/CharStreams', target file types: TypeScript, JavaScript, Declaration.
Directory '/Users/andy/antlr/node_modules/antlr4/src/antlr4/CharStreams' does not exist, skipping all lookups in it.
======== Module name './CharStreams' was not resolved. ========
```

The problem is the package isn't configured to preserve file extensions in imports within `.d.ts` files, right?  I wonder if this is something arethetypeswrong could catch?

**Comment by andrewbranch** [comment]
Ouch, yes indeed. Yeah, this kind of check is definitely on my radar. So far, none of the checks use the type checker, so things are pretty fast. This kind of analysis is basically just running tsc on the output, which will take a bit longer, but I think is worth it. Nice find!

**Comment by jedwards1211** [comment]
Ugh I would have caught the issue sooner if `tsc --init` didn't set `"skipLibCheck": true` by default...

**Comment by anothermh** [comment]
I would likewise to see `nodenext` support. For example, I'm troubleshooting https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/521 and testing this against `@google-cloud/functions-framework@3.2.0` would be useful, though I don't know for sure if this tool would be able to help me troubleshoot the problem even if it supported `nodenext`.

**Comment by andrewbranch** [comment]
node16 === nodenext right now.

**Comment by anothermh** [comment]
Thank you, I didn't realize that. It's all green checkmarks on that package so I guess it's back to the drawing board for me.

It's a great tool, thank you for building it.

**Comment by andrewbranch** [comment]
I think the issue you’re having is _kind of_ visible in the tool by what’s _not_ there.  `"@google-cloud/functions-framework"` and `"@google-cloud/functions-framework/testing"` show up as entrypoints, which indicates that there was a package.json `"exports"` and it didn’t include anything besides those two. The presence of `"exports"` explicitly prohibits importing subpaths outside of the ones listed in it. So a deep import like `@google-cloud/functions-framework/build/src/functions` cannot work. It’s not exposed by the package.

You also say in the issue that

> This error can be resolved by changing moduleResolution to node instead of nodenext

But be aware that this is Node’s rule, not TypeScript’s, so if you were dealing with runtime imports rather than type-only ones, you would be getting rid of a compile-time error, but would crash at runtime.

**Comment by anothermh** [comment]
I really appreciate your expertise here. Thank you for shedding some light on the problem even though it's off-topic from what the original poster asked about.

If I can ask you for your expert opinion, what do you think is the right way to resolve the issue I described so that I would be able to do a deep import? There are many types defined within the recesses of the package that I'd like to be able to access. With a little guidance I would be able to open a PR against the repo to try to encourage some progress from the Google team.

**Comment by anothermh** [comment]
Great answer, thank you.
