### ISSUE TITLE
typing exported JSON files

### ISSUE THREAD

**Issue by olivier-martin-sf** [arethetypeswrong/arethetypeswrong.github.io#3]
Thank you so much for this very useful tool. This issue is about asking questions relative to JSON files.

### Typings of exported JSON files

I've tried to run it against a package that my team is publishing and I am wondering what's the right approach for typings exported JSON files? For example, the following package exports declaration:

```json
"exports": {
   "./foo.json": "./dist/foo.json"
}
```

Result in the following errors:

> Imports of "package/foo.json" under all modern module resolution settings resolved to JavaScript files, but no types.

And:

> Imports of multiple entrypoints resolved to ES modules from a CJS importing module. CJS modules in Node will only be able to access this entrypoint with a dynamic import

### Ignoring exported package.json?

On a side note, shall we ignore the entry that exports the `package.json` when present? 

```json
"exports": {
  "./package.json": "./package.json",
}
```

Happy to do a PR if you think that should be the default.

Looking forward to the TS documentation updates.

**Comment by andrewbranch** [comment]
The message is slightly wrong for JSON files because unlike `.js` files, `.json` files have types inferred for them automatically as long as they resolve (some modes need to use `resolveJsonModule` for this; I have it turned on for the analysis). So, resolutions to JSON files should not be reported as a problem, though I think it would be nice to indicate what’s happening with them in some way, since in TypeScript 5.0.0, it’s possible to write types for a JSON file by using a `*.d.json.ts` extension.

I also think it’s nice to see the package.json subpath represented. In fact, it could be a good feature to _always_ try to resolve the package.json, so that it shows up as a legitimate failure if a package uses `exports` but forgot to add `package.json` to it (very easy to do until you need it!).

**Comment by olivier-martin-sf** [comment]
Thanks a lot for the detailed answer! Would you consider a PR that doesn't report JSON files as a problem?

> I think it would be nice to indicate what’s happening with them in some way since in TypeScript 5.0.0, it’s possible to write types for a JSON file by using a *.d.json.ts extension

Do you have suggestions on how to handle this?

**Comment by andrewbranch** [comment]
I’ll handle this soon. I appreciate the offer to contribute, but I’m not 100% sure how I want to represent this yet, and the code is a little too in flux (read: sloppy and unsure of its own abstractions) for me to encourage a PR at this point 😅. This was a real get-it-up-and-running-and-clean-it-up-later project.

**Comment by olivier-martin-sf** [comment]
Appreciate your honesty and transparency, thanks a lot!

**Comment by cseas** [comment]
I have a similar issue with css files. My package provides imports for css files:
https://github.com/hazel-ui/hazel-ui/blob/main/package.json#L10-L11

It should be safe to assume that css files are not going to have an accompanying declarations file and can be ignored.

**Comment by andrewbranch** [comment]
CSS files can certainly have accompanying declaration files

**Comment by andrewbranch** [comment]
I don’t know; this project is designed to give you information, not block a build like a linter. As a human, you can decide what information is relevant to your particular case. If I simply remove information, I give everyone less information, which seems strictly worse.

In the future, I would like to make a “severity” system to separate errors, warnings, and info. At that point, it would be reasonable to make untyped non-JS files an “info” instead of appearing to be a problem. And if there’s ever a CLI version of this tool, it would definitely make sense to be able to ignore certain severities or certain problem kinds. But for now, I don’t think it’s worth it to hide entrypoint information in these edge cases. Some people will have non-JS entrypoints that they definitely want to provide types for.
