### ISSUE TITLE
New problem kind: cjs-module-lexer incompatibility

### ISSUE THREAD

**Issue by andrewbranch** [arethetypeswrong/arethetypeswrong.github.io#35]
When node16-esm resolves to a CJS module with types, we should run https://github.com/nodejs/cjs-module-lexer on it and compare the named exports visible to Node with the ones visible to TypeScript, and error for any that TS says are available that wouldn’t work in Node.

**Comment by laverdet** [comment]
This isn't specific to CommonJS, since ESM types can also lie about their exports. In that case it would be a matter of parsing the source texts with esbuild and following the ESM linker specification which isn't terribly complicated.

I did some tinkering on this over here -- https://github.com/laverdet/arethetypeswrong.github.io/commit/c4450102ee521f14a8b669d108d37200cb869b14

I struggled a bit extracting the expected runtime exported names from typescript's API since I'm not super familiar with it. My simple implementation fails to differentiate between type-only exports and real exports. If you could point out how to extract that information then I could contribute an implementation which can statically determine the result of `Object.keys(await import(moduleName))` under nodejs. With those pieces in place it would just be a matter of a flat diff between the two array of export names.
